// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3E7CLaNQbOPyvhcnkaR6M29vQZTJ832Y',
    appId: '1:737393062351:web:a312d34ceb32d31ae9a2ba',
    messagingSenderId: '737393062351',
    projectId: 'alzheimerapp-a66e2',
    authDomain: 'alzheimerapp-a66e2.firebaseapp.com',
    storageBucket: 'alzheimerapp-a66e2.firebasestorage.app',
    measurementId: 'G-8L852QJ6YS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgGYs7_F27a67L5h4AEinqmIXb1oQ3e88',
    appId: '1:737393062351:android:6f6e58b373825b86e9a2ba',
    messagingSenderId: '737393062351',
    projectId: 'alzheimerapp-a66e2',
    storageBucket: 'alzheimerapp-a66e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-O0T0MyC48w8UV-ZPVtsqoQ_8T06QlIA',
    appId: '1:737393062351:ios:bd045470115f5897e9a2ba',
    messagingSenderId: '737393062351',
    projectId: 'alzheimerapp-a66e2',
    storageBucket: 'alzheimerapp-a66e2.firebasestorage.app',
    iosBundleId: 'com.example.alzheimersmartcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-O0T0MyC48w8UV-ZPVtsqoQ_8T06QlIA',
    appId: '1:737393062351:ios:bd045470115f5897e9a2ba',
    messagingSenderId: '737393062351',
    projectId: 'alzheimerapp-a66e2',
    storageBucket: 'alzheimerapp-a66e2.firebasestorage.app',
    iosBundleId: 'com.example.alzheimersmartcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3E7CLaNQbOPyvhcnkaR6M29vQZTJ832Y',
    appId: '1:737393062351:web:dbc0b50a057d20cbe9a2ba',
    messagingSenderId: '737393062351',
    projectId: 'alzheimerapp-a66e2',
    authDomain: 'alzheimerapp-a66e2.firebaseapp.com',
    storageBucket: 'alzheimerapp-a66e2.firebasestorage.app',
    measurementId: 'G-JTWSN4Q49H',
  );
}
